### PR TITLE
Rusty kendall matrix

### PR DESCRIPTION
**Pull request by CGMossa**
This is an entirely different focus.

Instead of parallelising the ici-kendall tau calculation itself, we parallelise the matrix calculation itself.

I've added in an example that I retrieved from here:
```r
# 1. DOWNLOAD the wine dataset from UCI:
URL  <- "ftp://ftp.ics.uci.edu/pub/machine-learning-databases/wine/wine.data"
wine <-  read.csv(URL, header = FALSE) 


# 2. SET variables' names as header:
colnames(wine) <- c('Type', 'Alcohol', 'Malic', 'Ash', 
                    'Alcalinity', 'Magnesium', 'Phenols', 
                    'Flavanoids', 'Nonflavanoids', 'Proanthocyanins',
                    'Color', 'Hue', 'Dilution', 'Proline')
wine %>% readr::write_csv("rustlib/data/wine.csv", col_names = TRUE)
```

This example, if rotated and made more cumbersome than it already is, yields a calculation time of 256 ms in R (using the non-parallel version), and is 8ms in Rust. The R split-up version spends 34 ms. 

In the Rust version, I am not using a parallelised version of the ici-kendall calculation.
This could also benefit the performance.

### CODE REVIEW

**Comment by CGMossa** [comment]
A cursory attempt at using ici-kendall-tau parallelised version resulted in worse performance.

I am yet to try out a bigger case and see what happens there.

**Comment by rmflight** [comment]
Looks very cool Mossa.

Only thing missing would be some instructions on installing and calling it, either from command line or from R. I'd like to verify the performance and output values, but I can't figure out how to run it ...

all the benchmarking is currently in Rust itself ...

Using `cargo bench`, I currently get the following error:

```
Gnuplot not found, using plotters backend
Benchmarking ici-kendall-tau mat wine: Warming up for 3.0000 sthread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', benches/kendall_tau_mat_bench.rs:15:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by CGMossa** [comment]
Let me quickly give out this instruction:

In the current directory, there should be a `/data/wine.csv` file and a `/result/` folder.
Use `mkdir` to create those. 

I have other comments, we should communicate about them.

**Comment by CGMossa** [comment]
Another benchmark: Given `big_matrix2` and running it on my (unreasonable) 12-core machine, we have: 7.66 ms on the `wine`-dataset and for the `big_matrix2` the benchmark is
```rust
Benchmarking ici-kendall-tau mat big matrix 2: Warming up for 3.0000 s
Warning: Unable to complete 100 samples in 5.0s. You may wish to increase target time to 1185.4s, or reduce sample count to 10.
ici-kendall-tau mat big matrix 2
                        time:   [9.1829 s 9.2050 s 9.2285 s]
Found 2 outliers among 100 measurements (2.00%)
  2 (2.00%) high mild
```

Memory usage was stable at 1.1gb, while cpu utilization was at 100%...

**Comment by rmflight** [comment]
Very cool Mossa. In my own test on my machine with the big matrix, assuming I've done it right, I got times of:

`time:   [29.893 s 30.152 s 30.438 s]`

Which is very close to my timings of 30 - 34s using all 8 cores using R & Rcpp(depends on whether I'm examining features or samples).

**Comment by CGMossa** [comment]
Alright, I was a bit disappointed that the rust-version performed like R/Rcpp, but what did I expect? I have translated the code exactly.

I've attempted three things:

1. There must be an approximation to correlation, in which one can go from `feature x feature` correlation matrix to `observation x observation` matrix. I'm sure of it, but I've not found a way to do it, or someone that has done it either. But it must be possible. If one scales a dataset `X`, then it should be possible to decompose the dataset matrix into components, that can be fit together, to yield a transformation from either a feature-specific correlation, or a samples-specific correlation. This is a dead end for now.
2. I've tried to profile the rust code using [Superluminal Performance](https://superluminal.eu/), but basically it says nothing. I could inject more focused places, to see where the bottlenecks are, but I've decided against it. Note that I tested the sequential setting and not the parallel setting.
3. I suspect that the biggest performance bottleneck is the copying (whenever it says `into_owned` or `clone`) is what is causing performance bottleneck. So instead of passing `Vec` or `ndarray::Array1` to the ici-kendall tau procedure, I've started to pass in references to the columns. This has required restructuring and altering some stuff. Now, the code runs, but the output is not correct. I cannot really figure out what I did wrong.. Maybe someone could take a cursory look? I'll push these changes now.

**Comment by rmflight** [comment]
Based on your description, I had something similar happen.

If I didn't clone X and Y in ICI-kendallt, I noticed that I also ended up
with wrong values, and also with X and Y in my R global environment being
modified with the imputed value.

Something similar could be happening here??

It may be that you have to do imputation of NA in the matrix code first,
and then you can avoid that step, and messing with copies and modifying the
input values in the kendall-t calculation itself??

I'll try and take an actual look at the code soon to see if anything else
jumps out.

**Comment by CGMossa** [comment]
Ohh I gotta push this, as I fixed some issues regarding the pairs..

**Comment by CGMossa** [comment]
I've now pushed versions that "work" but need inspection.
They do not run in parallel unless the feature is enabled through a flag `--features rayon`. See commit notes.
Thus for benchmarking, one has to use
`cargo bench --features rayon` for the parallel version.

**Comment by CGMossa** [comment]
Alright, absolutely last change: In order to parallelise the inner part (the ici-kendall calculation for a pair of variables), one may employ atomics in order to parallelise the loop. I've added these to it. So now, it can be enabled so that everything is parallelised in this...

However, the performance deltas for me are quite awful. I don't know why. 
But it is there now! Easy to tinker with (through code) and maybe could be informative somehow. 

I'll push this in a moment, but I don't think it is much better than what is currently up.

**Comment by andy-thomason** [comment]
@CGMossa pointed me at this. Good to see R and Rust combined. For performance, try to isolate the core of any loop into its own function and check the function on godbolt.org with "-O". Atomics on x86 have about a 400 cycle overhead and should be used sparingly. Rayon should partition into mutable chunks.

**Pull request closed without merging**
